#include "main.h"

#include <stdio.h>
#include <stdlib.h>


#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/thegame.h"
#include "images/sprite.h"
#include "images/winlose.h"
#include "images/sad.h"
#include "images/happy.h"
#include "images/blackscreen.h"


/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  INSTRUCTIONS,
  PLAY,
  WIN,
  LOSE,
};
enum gba_state state;
struct player p = {65, 105, 15, 15, 65, 105, 0, WHITE};
struct enemy e = {10, 10, 10, 10, 1, 1, 10, 10, YELLOW};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  


  state = START;
  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    
    switch (state) {
      case START:
        waitForVBlank();
        startScreen();
        if(KEY_DOWN(BUTTON_START, BUTTONS)) {
          instructions();
        }
        break;
      case INSTRUCTIONS:
        waitForVBlank();
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          startScreen();
        }
        if (KEY_DOWN(BUTTON_A, BUTTONS)) {
          playScreen();
        }
        break;
      case PLAY:
        waitForVBlank();
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          startScreen();
        }
        if (KEY_DOWN(BUTTON_LEFT, BUTTONS) && (p.col > 1) && KEY_DOWN(BUTTON_DOWN, BUTTONS) && (p.row < (HEIGHT - 15))){
          p.old_row = p.row;
          p.old_col = p.col;
          p.col = p.col - 2;
          p.row = p.row + 2;
        }
        if (KEY_DOWN(BUTTON_DOWN, BUTTONS) && (p.row < (HEIGHT - 15)) && KEY_DOWN(BUTTON_RIGHT, BUTTONS) && (p.col < (WIDTH - 15))){
          p.old_row = p.row;
          p.old_col = p.col;
          p.row = p.row + 2;
          p.col = p.col + 2; 
        }
        if (KEY_DOWN(BUTTON_RIGHT, BUTTONS) && (p.col < (WIDTH - 15)) && KEY_DOWN(BUTTON_UP, BUTTONS) && (p.row > 1)){
          p.old_row = p.row;
          p.old_col = p.col;
          p.row = p.row - 2;
          p.col = p.col + 2; 
        }
        if (KEY_DOWN(BUTTON_LEFT, BUTTONS) && (p.col > 1) && KEY_DOWN(BUTTON_UP, BUTTONS) && (p.row > 1)){
          p.old_row = p.row;
          p.old_col = p.col;
          p.col = p.col - 2; 
          p.row = p.row - 2;
        }



        if (KEY_DOWN(BUTTON_LEFT, BUTTONS) && !KEY_DOWN(BUTTON_DOWN, BUTTONS) && !KEY_DOWN(BUTTON_UP, BUTTONS) && (p.col > 1)){
          p.old_col = p.col;
          p.old_row = p.row;
          p.col = p.col - 2; 
        }
        if (KEY_DOWN(BUTTON_RIGHT, BUTTONS) && !KEY_DOWN(BUTTON_DOWN, BUTTONS) && !KEY_DOWN(BUTTON_UP, BUTTONS) && (p.col < (WIDTH - 15))){
          p.old_col = p.col;
          p.old_row = p.row;
          p.col = p.col + 2; 
        }
        if (KEY_DOWN(BUTTON_UP, BUTTONS) && !KEY_DOWN(BUTTON_RIGHT, BUTTONS) && !KEY_DOWN(BUTTON_LEFT, BUTTONS) && (p.row > 1)){
          p.old_row = p.row;
          p.old_col = p.col;
          p.row = p.row - 2;
        }
        if (KEY_DOWN(BUTTON_DOWN, BUTTONS) && !KEY_DOWN(BUTTON_RIGHT, BUTTONS) && !KEY_DOWN(BUTTON_LEFT, BUTTONS) && (p.row < (HEIGHT - 15))){
          p.old_row = p.row;
          p.old_col = p.col;
          p.row = p.row + 2;
        }
        

    
        if ((e.col < 1) || (e.col > (WIDTH - (e.width)))) {
          e.x_speed = (e.x_speed * (-1));
        if (randint(0,100) >= 50) {
          e.color = GREEN;
        } else {
          e.color = RED;
        }
        }
        if ((e.row < 1) || (e.row > (HEIGHT - (e.height)))) {
          e.y_speed = (e.y_speed * (-1));
          if (randint(0,100) >= 50) {
            e.color = GREEN;
          } else {
            e.color = RED;
          }
        }

        e.last_col = e.col;
        e.last_row = e.row;
        e.col = e.col + e.x_speed;
        e.row = e.row + e.y_speed;
        





        //draw ball
        //waitForVBlank();

        //waitForVBlank();
        drawRectDMA(e.last_row, e.last_col, e.width, e.height, BLACK);
        drawRectDMA(e.row, e.col, e.width, e.height, e.color);

        //draw player
          drawRectDMA(p.old_row, p.old_col, p.width, p.height, BLACK);
          drawRectDMA(p.row, p.col, p.height, p.width, p.color);
        //adding score counter
        
        
       
        char buffer[51];
        sprintf(buffer, "Score: %d", p.score);
        drawRectDMA(150, 5, 60, 10, BLACK);
        drawString(150, 5, buffer, BLUE);
        
        
        //deteching collision
        if ((e.col >= (p.col) && e.col <= p.col + p.width) && (e.row <= p.row + p.width && e.row >= p.row)) {
          if (e.color == RED) {
             p.score--;
          } else if (e.color == GREEN) {
             p.score++;
          }
        }
        if (p.score >= 50) {
          winScreen();
        }
        if (p.score < -10) {
          loseScreen();
        }
        
        break;
      case WIN:
        waitForVBlank();
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          startScreen();
        }
        break;
      case LOSE:
        waitForVBlank();
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          startScreen();
        }
        break;
    }
    waitForVBlank();

    previousButtons = currentButtons; // Store the current state of the buttons
  }

 

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}

//states for the game


//start state
void startScreen(void){
    waitForVBlank();
    drawFullScreenImageDMA(thegame);
    state = START;

}

//instructions state
void instructions(void){
    waitForVBlank();
    drawFullScreenImageDMA(BLACK);
    drawString(20, 20, "CATCH THE GREEN ENEMIES", GREEN);
    drawString(60, 20, "BUT YOU MUST DODGE THE RED ENEMIES", RED);
    drawString(100, 20, "PRESS A (Z) TO START", WHITE);
    state = INSTRUCTIONS;
}

//play/game state
void playScreen(void){
    waitForVBlank();
    drawFullScreenImageDMA(blackscreen);
    p.row = 65;
    p.col = 105;
    p.width = 15;
    p.height = 15;
    p.old_row = 65;
    p.old_col = 105;
    p.score = 0;
    p.color = WHITE;

    e.row = 10;
    e.col = 10;
    e.width = 10;
    e.height = 10;
    e.x_speed = 1;
    e.y_speed = 1;
    e.last_row = 10;
    e.last_col = 10;
    e.color = GREEN;


    state = PLAY;
}

//win screen
void winScreen(void){
    drawFullScreenImageDMA(winlose);
    drawCenteredString(40, 100, 40, 40, "YOU HAVE WON!", BLACK);
    drawImageDMA(80, 90, 60, 60, happy);
    state = WIN;
}

//lose screen
void loseScreen(void){
     drawFullScreenImageDMA(winlose);
     drawCenteredString(40, 100, 40, 40, "YOU HAVE LOST!", BLACK);
     drawImageDMA(80, 90, 60, 60, sad);
     state = LOSE;
}







