
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
#################################################
# file to edit: notebook.ipynb͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉

import numpy as np
import operator

def part_1_a():
    """Provide probabilities for the word HMMs outlined below.
    Word ALLIGATOR, NUTS, and SLEEP.
    Review Udacity Lesson 8 - Video #29. HMM Training
    Returns:
        tuple() of
        (prior probabilities for all states for word ALLIGATOR,
         transition probabilities between states for word ALLIGATOR,
         emission parameters tuple(mean, std) for all states for word ALLIGATOR,
         prior probabilities for all states for word NUTS,
         transition probabilities between states for word NUTS,
         emission parameters tuple(mean, std) for all states for word NUTS,
         prior probabilities for all states for word SLEEP,
         transition probabilities between states for word SLEEP,
         emission parameters tuple(mean, std) for all states for word SLEEP)
        Sample Format (not complete):
        (
            {'A1': prob_of_starting_in_A1, 'A2': prob_of_starting_in_A2, ...},
            {'A1': {'A1': prob_of_transition_from_A1_to_A1,
                    'A2': prob_of_transition_from_A1_to_A2,
                    'A3': prob_of_transition_from_A1_to_A3,
                    'Aend': prob_of_transition_from_A1_to_Aend},
             'A2': {...}, ...},
            {'A1': tuple(mean_of_A1, standard_deviation_of_A1),
             'A2': tuple(mean_of_A2, standard_deviation_of_A2), ...},
            {'N1': prob_of_starting_in_N1, 'N2': prob_of_starting_in_N2, ...},
            {'N1': {'N1': prob_of_transition_from_N1_to_N1,
                    'N2': prob_of_transition_from_N1_to_N2,
                    'N3': prob_of_transition_from_N1_to_N3,
                    'Nend': prob_of_transition_from_N1_to_Nend},
             'N2': {...}, ...}
            {'N1': tuple(mean_of_N1, standard_deviation_of_N1),
             'N2': tuple(mean_of_N2, standard_deviation_of_N2), ...},
            {'S1': prob_of_starting_in_S1, 'S2': prob_of_starting_in_S2, ...},
            {'S1': {'S1': prob_of_transition_from_S1_to_S1,
                    'S2': prob_of_transition_from_S1_to_S2,
                    'S3': prob_of_transition_from_S1_to_S3,
                    'Send': prob_of_transition_from_S1_to_Send},
             'S2': {...}, ...}
            {'S1': tuple(mean_of_S1, standard_deviation_of_S1),
             'S2': tuple(mean_of_S2, standard_deviation_of_S2), ...}
        )
    """

    # TODO: complete this function.͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉


    """Word ALLIGATOR"""
    a_prior_probs = {
        'A1': 0.333,
        'A2': 0.0,
        'A3': 0.0,
        'Aend': 0.0
    }
    a_transition_probs = {
        'A1': {'A1': 0.833, 'A3': 0.0, 'A2': 0.167, 'Aend': 0.0},
        'A2': {'A1': 0.0, 'A2': 0.786, 'A3': 0.214, 'Aend': 0.0},
        'A3': {'A2': 0.0, 'A3': 0.727, 'A1': 0.0, 'Aend': 0.273},
        'Aend': {'A1': 0.0, 'A3': 0.0, 'A2': 0.0, 'Aend': 1.0}
    }
    # Parameters for end state is not required͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
    a_emission_paras = {
        'A1': (51.056, 21.986),
        'A2': (28.357, 14.936),
        'A3': (53.727, 16.707),
        'Aend': (None, None)
    }

    """Word NUTS"""
    n_prior_probs = {
        'N1': 0.333,
        'N2': 0.0,
        'N3': 0.0,
        'Nend': 0.0
    }
    # Probability of a state changing to another state.͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
    n_transition_probs = {
        'N1': {'N3': 0.0, 'N1': 0.919, 'N2': 0.081, 'Nend': 0.0},
        'N2': {'N3': 1.000, 'N1': 0.0, 'N2': 0.0, 'Nend': 0.0},
        'N3': {'N3': 0.625, 'N1': 0.0, 'N2': 0.0, 'Nend': 0.375},
        'Nend': {'N3': 0.0, 'N2': 0.0, 'N1': 0.0, 'Nend': 1.0}
    }
    # Parameters for end state is not required͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
    n_emission_paras = {
        'N1': (38.081, 11.175),
        'N2': (42.000, 2.828),
        'N3': (60.000, 13.491),
        'Nend': (None, None)
    }

    """Word SLEEP"""
    s_prior_probs = {
        'S1': 0.333,
        'S2': 0.0,
        'S3': 0.0,
        'Send': 0.0
    }
    s_transition_probs = {
        'S1': {'S2': 0.375, 'S3': 0.0, 'S1': 0.625, 'Send': 0.0},
        'S2': {'S1': 0.0, 'S2': 0.864, 'S3': 0.136, 'Send': 0.0},
        'S3': {'S2': 0.0, 'S1': 0.0, 'S3': 0.0, 'Send': 1.0},
        'Send': {'S2': 0.0, 'S3': 0.0, 'S1': 0.0, 'Send': 1.0}
    }
    # Parameters for end state is not required͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
    s_emission_paras = {
        'S1': (29.500, 8.411),
        'S2': (36.182, 5.990),
        'S3': (36.667, 1.886),
        'Send': (None, None)
    }

    return (a_prior_probs, a_transition_probs, a_emission_paras,
            n_prior_probs, n_transition_probs, n_emission_paras,
            s_prior_probs, s_transition_probs, s_emission_paras)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉

def gaussian_prob(x, para_tuple):
    """Compute the probability of a given x value

    Args:
        x (float): observation value
        para_tuple (tuple): contains two elements, (mean, standard deviation)

    Return:
        Probability of seeing a value "x" in a Gaussian distribution.

    Note:
        We simplify the problem so you don't have to take care of integrals.
        Theoretically speaking, the returned value is not a probability of x,
        since the probability of any single value x from a continuous
        distribution should be zero, instead of the number outputted here.
        By definition, the Gaussian percentile of a given value "x"
        is computed based on the "area" under the curve, from left-most to x.
        The probability of getting value "x" is zero because a single value "x"
        has zero width, however, the probability of a range of value can be
        computed, for say, from "x - 0.1" to "x + 0.1".

    """
    if list(para_tuple) == [None, None]:
        return 0.0

    mean, std = para_tuple
    gaussian_percentile = (2 * np.pi * std**2)**-0.5 * \
                          np.exp(-(x - mean)**2 / (2 * std**2))
    return gaussian_percentile



def viterbi(evidence_vector, states, prior_probs,
            transition_probs, emission_paras):
    """Viterbi Algorithm to calculate the most likely states give the evidence.
    Args:
        evidence_vector (list): List of right hand Y-axis positions (integer).
        states (list): List of all states in a word. No transition between words.
                       example: ['A1', 'A2', 'A3', 'Aend', 'N1', 'N2', 'N3', 'Nend']
        prior_probs (dict): prior distribution for each state.
                            example: {'X1': 0.25,
                                      'X2': 0.25,
                                      'X3': 0.25,
                                      'Xend': 0.25}
        transition_probs (dict): dictionary representing transitions from each
                                 state to every other valid state such as for the above
                                 states, there won't be a transition from 'A1' to 'N1'
        emission_paras (dict): parameters of Gaussian distribution
                                from each state.
    Return:
        tuple of
        ( A list of states the most likely explains the evidence,
          probability this state sequence fits the evidence as a float )
    Note:
        You are required to use the function gaussian_prob to compute the
        emission probabilities.
    """

    # TODO: complete this function.͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉

    sequence = []
    probability = 0.0


    #if empty, return null
    if len(evidence_vector) == 0:
        return (None, 0)


    #make two tables, one for back tracing the other for probability calculations
    K = len(states)
    T = len(evidence_vector)
    table = np.zeros(shape=(K,T))
    back = np.zeros(shape=(K,T))
    path = np.zeros(T, dtype = int)

    #intial probabilities for the states
    for element in range(0, K):
        table[element][0] = prior_probs[states[element]] * gaussian_prob(evidence_vector[0], emission_paras[states[element]])

    #loop through all samples, and then for each sample, loop through three states
    for j in range(1, T):
        for i in range(K):
            probabilities = []
            for k in range(K):
                currState = states[k]
                nextState = states[i]
                currentSample = evidence_vector[j]
                if nextState in transition_probs[currState]:
                    last = table[k][j-1]
                    calc = (last) * ((transition_probs[currState])[nextState]) * (gaussian_prob(currentSample, emission_paras[nextState]))
                    probabilities.append(calc)
                else:
                    probabilities.append(0)

            #finds max value in the probability list, then insert val in table & insert index into backing table
            topVal = max(probabilities)
            (table[i])[j] = topVal
            (back[i])[j] = probabilities.index(topVal)

    #using backing Table & tracing optimal path
    samples = (len(evidence_vector) - 1)
    prev = np.argmax(table[:, samples])
    path[samples] = prev

    for i in range(samples, 0, -1):
        path[i-1] = int(back[int(path[i])][i])

    for val in path:
        sequence.append(states[val])
    probability = table[prev][samples]



    return sequence, probability






########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉

def part_2_a():
    """Provide probabilities for the word HMMs outlined below.
    Now, at each time frame you are given 2 observations (right hand Y
    position & right thumb Y position). Use the result you derived in
    part_1_a, accompany with the provided probability for right thumb, create
    a tuple of (right-hand-y, right-thumb-y) to represent high-dimension transition &
    emission probabilities.
    """

     # TODO: complete this function.͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
    raise NotImplementedError()

    """Word ALLIGATOR"""
    a_prior_probs = {
        'A1': 0.,
        'A2': 0.,
        'A3': 0.,
        'Aend': 0.
    }
    # example: {'A1': {'A1' : (right-hand Y, right-thumb Y), ... }͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
    a_transition_probs = {
        'A1': {'A2': (0., 0.), 'A3': (0., 0.), 'A1': (0., 0.), 'Aend': (0., 0.)},
        'A2': {'A2': (0., 0.), 'A1': (0., 0.), 'A3': (0., 0.), 'Aend': (0., 0.)},
        'A3': {'A1': (0., 0.), 'A2': (0., 0.), 'A3': (0., 0.), 'Aend': (0., 0.)},
        'Aend': {'A2': (0., 0.), 'A1': (0., 0.), 'A3': (0., 0.), 'Aend': (0., 0.)}
    }
    # example: {'A1': [(right-hand-mean, right-thumb-std), (right-hand--mean, right-thumb-std)] ...}͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
    a_emission_paras = {
        'A1': [(None, None), (None, None)],
        'A2': [(None, None), (None, None)],
        'A3': [(None, None), (None, None)],
        'Aend': [(None, None), (None, None)]
    }

    """Word NUTS"""
    n_prior_probs = {
        'N1': 0.,
        'N2': 0.,
        'N3': 0.,
        'Nend': 0.
    }
    n_transition_probs = {
        'N1': {'N3': (0., 0.), 'N1': (0., 0.), 'N2': (0., 0.), 'Nend': (0., 0.)},
        'N2': {'N1': (0., 0.), 'N3': (0., 0.), 'N2': (0., 0.), 'Nend': (0., 0.)},
        'N3': {'N1': (0., 0.), 'N3': (0., 0.), 'N2': (0., 0.), 'Nend': (0., 0.)},
        'Nend': {'N1': (0., 0.), 'N2': (0., 0.), 'N3': (0., 0.), 'Nend': (0., 0.)}
    }
    n_emission_paras = {
        'N1': [(None, None), (None, None)],
        'N2': [(None, None), (None, None)],
        'N3': [(None, None), (None, None)],
        'Nend': [(None, None), (None, None)]
    }

    """Word SLEEP"""
    s_prior_probs = {
        'S1': 0.,
        'S2': 0.,
        'S3': 0.,
        'Send': 0.
    }
    s_transition_probs = {
        'S1': {'S2': (0., 0.), 'S3': (0., 0.), 'S1': (0., 0.), 'Send': (0., 0.)},
        'S2': {'S1': (0., 0.), 'S3': (0., 0.), 'S2': (0., 0.), 'Send': (0., 0.)},
        'S3': {'S3': (0., 0.), 'S1': (0., 0.), 'S2': (0., 0.), 'Send': (0., 0.)},
        'Send': {'S3': (0., 0.), 'S1': (0., 0.), 'S2': (0., 0.), 'Send': (0., 0.)}
    }
    s_emission_paras = {
        'S1': [(None, None), (None, None)],
        'S2': [(None, None), (None, None)],
        'S3': [(None, None), (None, None)],
        'Send': [(None, None), (None, None)]
    }

    return (a_prior_probs, a_transition_probs, a_emission_paras,
            n_prior_probs, n_transition_probs, n_emission_paras,
            s_prior_probs, s_transition_probs, s_emission_paras)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉

def multidimensional_viterbi(evidence_vector, states, prior_probs,
                             transition_probs, emission_paras):
    """Decode the most likely word phrases generated by the evidence vector.
    States, prior_probs, transition_probs, and emission_probs will now contain
    all the words from part_2_a.
    Evidence vector is a list of tuples where the first element of each tuple is the right
    hand coordinate and the second element is the right thumb coordinate.
    """
    # TODO: complete this function.͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
    raise NotImplementedError()

    sequence = []
    probability = 0.0

    return sequence, probability

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉

def return_your_name():
    """Return your name
    """
    # TODO: finish this͏︆͏󠄃͏󠄌͏󠄍͏󠄂͏️͏󠄄͏︂͏󠄉

    return "Jadon Co"